let galleryItems = [GalleryItem(image: #imageLiteral(resourceName: "beauty"), department: "home", description: "beauty", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "beauty-2"), department: "home", description: "beauty-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "flowers"), department: "home", description: "flowers", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "flowers-2"), department: "home", description: "flowers-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food"), department: "food", description: "food", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-2"), department: "food", description: "food-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-3"), department: "food", description: "food-3", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-4"), department: "food", description: "food-4", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture"), department: "home", description: "furniture", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-2"), department: "home", description: "furniture-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-3"), department: "home", description: "furniture-3", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-4"), department: "home", description: "furniture-4", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-5"), department: "home", description: "furniture-5", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "gift"), department: "home", description: "gift", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid"), department: "kids", description: "kid", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-2"), department: "kids", description: "kid-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-3"), department: "kids", description: "kid-3", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-4"), department: "kids", description: "kid-4", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "man"), department: "men", description: "man", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "man-2"), department: "men", description: "man-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "shoes"), department: "women", description: "shoes", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman"), department: "women", description: "woman", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-2"), department: "women", description: "woman-2", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-3"), department: "women", description: "woman-3", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-4"), department: "women", description: "woman-4", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-5"), department: "women", description: "woman-5", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-6"), department: "women", description: "woman-6", submittedBy: "splebbo", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-7"), department: "women", description: "woman-7", submittedBy: "splebbo", date: "3 Feb 2018")]

let products = [Product(image: #imageLiteral(resourceName: "dressing-gown"), title: "Dressing gown", price: "£19.99"), Product(image: #imageLiteral(resourceName: "bra"), title: "Bra", price: "£9.99"), Product(image: #imageLiteral(resourceName: "vase"), title: "Tulips", price: "£5.99")]
