let galleryItems = [GalleryItem(image: #imageLiteral(resourceName: "beauty"), department: "home", description: "beauty", submittedBy: "Sebastien", date: "25 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "beauty-2"), department: "home", description: "beauty-2", submittedBy: "Sevim", date: "24 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "flowers"), department: "home", description: "flowers", submittedBy: "Rosie", date: "23 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "flowers-2"), department: "home", description: "flowers-2", submittedBy: "Simon", date: "22 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food"), department: "food", description: "food", submittedBy: "Charles", date: "21 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-2"), department: "food", description: "food-2", submittedBy: "Christian", date: "20 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-3"), department: "food", description: "food-3", submittedBy: "Sophie", date: "19 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "food-4"), department: "food", description: "food-4", submittedBy: "Ryan", date: "18 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture"), department: "home", description: "furniture", submittedBy: "Lisa", date: "17 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-2"), department: "home", description: "furniture-2", submittedBy: "Mark", date: "16 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-3"), department: "home", description: "furniture-3", submittedBy: "Elliot", date: "15 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-4"), department: "home", description: "furniture-4", submittedBy: "Paul", date: "14 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "furniture-5"), department: "home", description: "furniture-5", submittedBy: "Joeseph", date: "13 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "gift"), department: "home", description: "gift", submittedBy: "Rebecca", date: "12 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid"), department: "kids", description: "kid", submittedBy: "Shaun", date: "11 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-2"), department: "kids", description: "kid-2", submittedBy: "Paul", date: "10 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-3"), department: "kids", description: "kid-3", submittedBy: "Milo", date: "9 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "kid-4"), department: "kids", description: "kid-4", submittedBy: "Jack", date: "8 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "man"), department: "men", description: "man", submittedBy: "John", date: "7 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "man-2"), department: "men", description: "man-2", submittedBy: "Alex", date: "6 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "shoes"), department: "women", description: "shoes", submittedBy: "Sam", date: "5 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman"), department: "women", description: "woman", submittedBy: "Leena", date: "4 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-2"), department: "women", description: "woman-2", submittedBy: "Josh", date: "3 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-3"), department: "women", description: "woman-3", submittedBy: "Luke", date: "2 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-4"), department: "women", description: "woman-4", submittedBy: "Reece", date: "1 Feb 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-5"), department: "women", description: "woman-5", submittedBy: "Benjamin", date: "31 Jan 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-6"), department: "women", description: "woman-6", submittedBy: "Liam", date: "30 Jan 2018"),
              GalleryItem(image: #imageLiteral(resourceName: "woman-7"), department: "women", description: "woman-7", submittedBy: "Noah", date: "29 Jan 2018")]

let products = [Product(image: #imageLiteral(resourceName: "men-top"), title: "Jacket", price: "£39.99", department: "men"),
                Product(image: #imageLiteral(resourceName: "men-trousers"), title: "Chinos", price: "£19.99", department: "men"),
                Product(image: #imageLiteral(resourceName: "women-top"), title: "Top", price: "£9.99", department: "women"),
                Product(image: #imageLiteral(resourceName: "women-trousers"), title: "Trousers", price: "£19.99", department: "women"),
                Product(image: #imageLiteral(resourceName: "home-bed"), title: "Bedding", price: "£49.99", department: "home"),
                Product(image: #imageLiteral(resourceName: "home-towels"), title: "Towels", price: "£5.99", department: "home"),
                Product(image: #imageLiteral(resourceName: "cheese"), title: "Cheese", price: "£19.99", department: "food"),
                Product(image: #imageLiteral(resourceName: "ham"), title: "Ham", price: "£19.99", department: "food"),
                Product(image: #imageLiteral(resourceName: "kids-boy"), title: "Jumper", price: "£9.99", department: "kids"),
                Product(image: #imageLiteral(resourceName: "kids-girl"), title: "Dress", price: "£14.99", department: "kids")]
